id: I25C05128
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:58:12+00:00'
last_modified: '2022-06-07T17:02:51.075753+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25104
  title: དུས་ཀྱི་འཁོར་ལོའི་འཆད་ཐབས་ཀྱི་ཟིན་བྲིས་ལེགས་བཤད་གསལ་བའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88BA:
      image_group_id: I3859
      title: ''
      total_pages: 88
      order: 1
      base_file: 88BA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
