id: P003018
initial_creation_type: ocr
source_metadata:
  id: bdr:W25104
  title: དུས་ཀྱི་འཁོར་ལོའི་འཆད་ཐབས་ཀྱི་ཟིན་བྲིས་ལེགས་བཤད་གསལ་བའི་མེ་ལོང
  author: ''
  volumes:
    150a78994fe44c9ea10a25f37d9b6da5:
      image_group_id: I3859
      title: ''
      volume_number: 1
      total_pages: 88
      base_file: v001.txt
